services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /opt/storage:/opt/storage
    env_file:
      - .env
    depends_on:
      - db
    command: bun run src/index.ts
    working_dir: /app
    restart: unless-stopped

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: FileManagement
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:


  # it's no working, so, let's stop this, can you help me make a docker-compose file as optimized as possible, that builds a docker image, lets the docker image app access files from the local machine, and takes the environment variables from the app .env file, and runs a PostgreSQL on it's default port and exposes it, ah, before i forget, the app is a ElysiaJs app running on bunJs and uses prisma, please make it as explicit as possible

