services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - storage-volume:/opt/storage
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongodb:27017/mydb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mydb

volumes:
  mongo-data:
  storage-volume: